- name: create a forwarding rule for https
  google.cloud.gcp_compute_firewall:
    name: freetier-allow-https
    network: "{{ network }}"
    allowed:
      - ip_protocol: tcp
        ports:
          - "443-443"
    source_ranges:
      - "0.0.0.0/0"  # Allow https access from anywhere
    direction: INGRESS
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: allow SSH traffic (port 22) from anywhere
  google.cloud.gcp_compute_firewall:
    name: freetier-allow-ssh22
    network: "{{ network }}"
    allowed:
      - ip_protocol: tcp
        ports:
          - "22-22"
    source_ranges:
      - "0.0.0.0/0"  # Allow SSH access from anywhere
    direction: INGRESS
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: allow SSH traffic on changed port {{ ssh_port }} from anywhere
  google.cloud.gcp_compute_firewall:
    name: freetier-allow-ssh-changed-port
    network: "{{ network }}"
    allowed:
      - ip_protocol: tcp
        ports:
          - "{{ ssh_port }}-{{ ssh_port }}"
    source_ranges:
      - "0.0.0.0/0"  # Allow SSH access from anywhere
    direction: INGRESS
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: allow traccar freematics traffic INGRESS
  google.cloud.gcp_compute_firewall:
    name: freetier-allow-traccar-freematics-ingress
    network: "{{ network }}"
    allowed:
      - ip_protocol: udp
        ports:
          - "5170-5170"
    source_ranges:
      - "0.0.0.0/0"
    direction: INGRESS
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: allow traccar osmand traffic INGRESS
  google.cloud.gcp_compute_firewall:
    name: freetier-allow-traccar-osmand-ingress
    network: "{{ network }}"
    allowed:
      - ip_protocol: tcp
        ports:
          - "5055-5055"
    source_ranges:
      - "0.0.0.0/0"
    direction: INGRESS
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: Wait a few seconds after creating firewall rules
  pause:
    seconds: 5