- name: Make keyring dir
  become: true
  become_method: sudo
  shell: mkdir -p /etc/apt/keyrings

- name: Download key
  become: true
  become_method: sudo
  shell: curl -fsSL https://archive.heckel.io/apt/pubkey.txt | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/archive.heckel.io.gpg

- name: Install apt-transport-https package
  become: true
  apt:
    name:
      - apt-transport-https
    state: present

- name: Add key
  become: true
  become_method: sudo
  shell: sudo sh -c "echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/archive.heckel.io.gpg] https://archive.heckel.io/apt debian main' > /etc/apt/sources.list.d/archive.heckel.io.list"

- name: Update package cache
  become: true
  block:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes

- name: Install ntfy packages
  become: true
  apt:
    update_cache: yes
    name:
      - ntfy
      - apt-transport-https
    state: present

- name: Copy ntfy config file server.yml
  become: true
  template:
    src: "templates/server.yml"
    dest: /etc/ntfy/server.yml

- name: Start ntfy
  become: true
  service:
    name: ntfy
    state: restarted
    enabled: yes

- name: Ntfy remove tokens of user
  include_tasks: ntfy_remove_all_tokens.yaml
  loop: "{{ ntfy_users }}"
  loop_control:
    loop_var: ntfy_user
  when: ntfy_users != None and ntfy_users | length > 0 and ntfy_user.reset_token is true

- name: Ntfy create users
  include_tasks: ntfy_create_user.yaml
  loop: "{{ ntfy_users }}"
  loop_control:
    loop_var: ntfy_user
