- name: Update apt and install packages
  become: true
  block:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 86400

    - name: Install packages
      become: true
      apt:
        name:
          - mc
          - git
          - tmux
          - htop
          - nano
          - gpg
          - python3-pexpect
        state: present